name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Укажите версию Node.js, которая вам нужна
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: npm run build # Замените на вашу команду сборки, если она отличается

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
